modLoader="javafml"
loaderVersion="[35,)" 
license="LGPL 2.1"
authors="Sirttas"

[[mods]] 
modId="elementalcraft"
version="${file.jarVersion}"
displayName="ElementalCraft"
description='''ElementalCraft is a magic mod based around the 4 elements: fire, water, earth and air.'''

[[dependencies.elementalcraft]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.13,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="dpanvil"
    mandatory=true
    versionRange="[1.16.3-1.0.7,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="jei"
    mandatory=false
    versionRange="[FORGE-1.16.3-7.6,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.elementalcraft]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.16.2-47,)"
    ordering="AFTER"
    side="BOTH"
    